### ISSUE TITLE
Redis problème implémentation

### ISSUE THREAD

**Issue by SebastienBtr** [EricLegoubin/emn-fila1-2018-spring-project#1]
Nous rencontrons des difficultés lors de l'implémentation de redis dans notre projet (course projeté).
Le server redis fonctionne mais lors de l'implémentation on a cette erreur : 

`org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jedisConnectionFactory' defined in org.emn.fila1.spring.project.CopApplication: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.redis.connection.jedis.JedisConnectionFactory]: Factory method 'jedisConnectionFactory' threw exception; nested exception is java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: redis/clients/jedis/Tuple`

On pense que le problème viens de l'utilisation de jedis [ici](https://github.com/EricLegoubin/emn-fila1-2018-spring-project/blob/COP/src/main/java/org/emn/fila1/spring/project/CopApplication.java)

ou d'un problème de version (jedis 2.9.0 et 2.0.0 pour redis) ou dépendance.

**Comment by EricLegoubin** [comment]
Bonsoir Sebastien

Est ce que le code est sous Github ? Je vais regarder

Cordialement

Eric

Envoyé de mon iPhone

Le 15 mars 2018 à 18:14, SebastienBtr <notifications@github.com<mailto:notifications@github.com>> a écrit :


Nous rencontrons des difficultés lors de l'implémentation de redis dans notre projet (course projeté).
Le server redis fonctionne mais lors de l'implémentation on a cette erreur :

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jedisConnectionFactory' defined in org.emn.fila1.spring.project.CopApplication: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.redis.connection.jedis.JedisConnectionFactory]: Factory method 'jedisConnectionFactory' threw exception; nested exception is java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: redis/clients/jedis/Tuple

On pense que le problème viens de l'utilisation de jedis ici<https://github.com/EricLegoubin/emn-fila1-2018-spring-project/blob/COP/src/main/java/org/emn/fila1/spring/project/CopApplication.java>

ou d'un problème de version (jedis 2.9.0 et 2.0.0 pour redis) ou dépendance.

**Comment by SebastienBtr** [comment]
Oui tout est sur la branche COP,

Cordialement.

**Comment by EricLegoubin** [comment]
Pour précision, j'ai pris la dernière version de Redis packagé sous Windows : 3.2.100, 64 bit
